inherit_from:
  - https://raw.githubusercontent.com/thoughtbot/guides/main/ruby/.rubocop.yml

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 120

Metrics/PerceivedComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: true
