version: "3"
services:
  app:
    # env_file:
    #   - .env.example
    #   - .env.test
    build:
      context: .
      dockerfile: Dockerfile
    command: "bundle exec rspec"
    environment:
      - RAILS_ENV=test
      - RACK_ENV=test
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES:-true}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT:-true}
      - SECRET_KEY_BASE=secret_key_base
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_NAME=mockr_test
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mockr_test
